<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Root[
	<!ELEMENT Root (NodoCella+)>
	<!ELEMENT NodoCella (id,XCOR,YCOR,text,down,up,laterale,laterale1*,laterale2*,laterale3*,laterale4*,laterale5*,laterale6*)>
	<!ELEMENT id (#PCDATA)>
	<!ELEMENT XCOR (#PCDATA)>
	<!ELEMENT YCOR (#PCDATA)>
	<!ELEMENT down (#PCDATA)>
	<!ELEMENT up (#PCDATA)>
	<!ELEMENT text (#PCDATA)>
	<!ELEMENT laterale (#PCDATA)>
	<!ELEMENT laterale1 (#PCDATA)>
	<!ELEMENT laterale2 (#PCDATA)>
	<!ELEMENT laterale3 (#PCDATA)>
	<!ELEMENT laterale4 (#PCDATA)>
	<!ELEMENT laterale5 (#PCDATA)>
	<!ELEMENT laterale6 (#PCDATA)>
]>


<Root>

	<NodoCella>
		<id>-1</id>
		<XCOR>415</XCOR>
		<YCOR>260</YCOR>
		<text>start</text>
		<down></down>
		<up></up>
		<laterale></laterale>
		<laterale1>52</laterale1>
		<laterale2>59</laterale2>
		<laterale3>65</laterale3>
		<laterale4>70</laterale4>
		<laterale5>76</laterale5>
		<laterale6>82</laterale6>
	</NodoCella>

	<NodoCella>
		<id>1</id>
		<XCOR>390</XCOR>
		<YCOR>50</YCOR>
		<text>isola vetro</text>
		<down>47</down>
		<up>2</up>
		<laterale></laterale>
	</NodoCella>

	<NodoCella>
		<id>2</id>
		<XCOR>435</XCOR>
		<YCOR>50</YCOR>
		<text>jolly</text>
		<down>1</down>
		<up>3</up>
		<laterale></laterale>

	</NodoCella>

	<NodoCella>
		<id>3</id>
		<XCOR>480</XCOR>
		<YCOR>50</YCOR>
		<text>centoMetallo</text>
		<down>2</down>
		<up>4</up>
		<laterale></laterale>

	</NodoCella>


	<NodoCella>
		<id>4</id>
		<XCOR>520</XCOR>
		<YCOR>50</YCOR>
		<text>centoOrg</text>
		<down>3</down>
		<up>5</up>
		<laterale></laterale>

	</NodoCella>

	<NodoCella>
		<id>5</id>
		<XCOR>570</XCOR>
		<YCOR>50</YCOR>
		<text>centoCarta</text>
		<down>4</down>
		<up>6</up>
		<laterale></laterale>

	</NodoCella>

	<NodoCella>
		<id>6</id>
		<XCOR>615</XCOR>
		<YCOR>70</YCOR>
		<text>jolly</text>
		<down>5</down>
		<up>7</up>
		<laterale>48</laterale>

	</NodoCella>


	<NodoCella>
		<id>7</id>
		<XCOR>650</XCOR>
		<YCOR>100</YCOR>
		<text>centoVetro</text>
		<down>6</down>
		<up>8</up>
		<laterale></laterale>

	</NodoCella>

	<NodoCella>
		<id>8</id>
		<XCOR>700</XCOR>
		<YCOR>120</YCOR>
		<text>centoPlastica</text>
		<down>7</down>
		<up>9</up>
		<laterale></laterale>

	</NodoCella>

	<NodoCella>
		<id>9</id>
		<XCOR>730</XCOR>
		<YCOR>140</YCOR>
		<text>imprevisti</text>
		<down>8</down>
		<up>10</up>
		<laterale></laterale>

	</NodoCella>

	<NodoCella>
		<id>10</id>
		<XCOR>750</XCOR>
		<YCOR>170</YCOR>
		<text>cinqIndif</text>
		<down>9</down>
		<up>11</up>
		<laterale></laterale>

	</NodoCella>

	<NodoCella>
		<id>11</id>
		<XCOR>790</XCOR>
		<YCOR>190</YCOR>
		<text>cinqOrg</text>
		<down>10</down>
		<up>12</up>
		<laterale></laterale>

	</NodoCella>

	<NodoCella>
		<id>12</id>
		<XCOR>830</XCOR>
		<YCOR>220</YCOR>
		<text>jolly</text>
		<down>11</down>
		<up>13</up>
		<laterale></laterale>

	</NodoCella>

	<NodoCella>
		<id>13</id>
		<XCOR>820</XCOR>
		<YCOR>255</YCOR>
		<text>cinqCarta</text>
		<down>12</down>
		<up>14</up>
		<laterale>53</laterale>

	</NodoCella>

	<NodoCella>
		<id>14</id>
		<XCOR>820</XCOR>
		<YCOR>290</YCOR>
		<text>cinqVetro</text>
		<down>13</down>
		<up>15</up>
		<laterale></laterale>

	</NodoCella>

	<NodoCella>
		<id>15</id>
		<XCOR>820</XCOR>
		<YCOR>325</YCOR>
		<text>centoPlastica</text>
		<down>14</down>
		<up>16</up>
		<laterale></laterale>

	</NodoCella>

	<NodoCella>
		<id>16</id>
		<XCOR>805</XCOR>
		<YCOR>360</YCOR>
		<text>centoMetallo</text>
		<down>15</down>
		<up>17</up>
		<laterale></laterale>
	</NodoCella>

	<NodoCella>
		<id>17</id>
		<XCOR>780</XCOR>
		<YCOR>390</YCOR>
		<text>imprevisti</text>
		<down>16</down>
		<up>18</up>
		<laterale></laterale>

	</NodoCella>

	<NodoCella>
		<id>18</id>
		<XCOR>750</XCOR>
		<YCOR>420</YCOR>
		<text>centoIndif</text>
		<down>17</down>
		<up>19</up>
		<laterale></laterale>

	</NodoCella>

	<NodoCella>
		<id>19</id>
		<XCOR>710</XCOR>
		<YCOR>440</YCOR>
		<text>cinqCarta</text>
		<down>18</down>
		<up>20</up>
		<laterale></laterale>

	</NodoCella>

	<NodoCella>
		<id>20</id>
		<XCOR>640</XCOR>
		<YCOR>450</YCOR>
		<text>dieciPlastica</text>
		<down>19</down>
		<up>21</up>
		<laterale>60</laterale>

	</NodoCella>

	<NodoCella>
		<id>21</id>
		<XCOR>610</XCOR>
		<YCOR>470</YCOR>
		<text>jolly</text>
		<down>20</down>
		<up>22</up>
		<laterale></laterale>

	</NodoCella>

	<NodoCella>
		<id>22</id>
		<XCOR>565</XCOR>
		<YCOR>470</YCOR>
		<text>centoCarta</text>
		<down>21</down>
		<up>23</up>
		<laterale></laterale>

	</NodoCella>

	<NodoCella>
		<id>23</id>
		<XCOR>520</XCOR>
		<YCOR>470</YCOR>
		<text>imprevisti</text>
		<down>22</down>
		<up>24</up>
		<laterale></laterale>

	</NodoCella>


	<NodoCella>
		<id>24</id>
		<XCOR>470</XCOR>
		<YCOR>470</YCOR>
		<text>cinqMetallo</text>
		<down>23</down>
		<up>25</up>
		<laterale></laterale>

	</NodoCella>

	<NodoCella>
		<id>25</id>
		<XCOR>425</XCOR>
		<YCOR>470</YCOR>
		<text>isola indifferenziata</text>
		<down>24</down>
		<up>26</up>
		<laterale></laterale>
	</NodoCella>

	<NodoCella>
		<id>26</id>
		<XCOR>380</XCOR>
		<YCOR>470</YCOR>
		<text>centoOrg</text>
		<down>25</down>
		<up>27</up>
		<laterale></laterale>
	</NodoCella>

	<NodoCella>
		<id>27</id>
		<XCOR>335</XCOR>
		<YCOR>470</YCOR>
		<text>imprevisti</text>
		<down>26</down>
		<up>28</up>
		<laterale></laterale>
	</NodoCella>

	<NodoCella>
		<id>28</id>
		<XCOR>290</XCOR>
		<YCOR>470</YCOR>
		<text>centoVetro</text>
		<down>27</down>
		<up>29</up>
		<laterale></laterale>
	</NodoCella>

	<NodoCella>
		<id>29</id>
		<XCOR>245</XCOR>
		<YCOR>470</YCOR>
		<text>cinqPlastica</text>
		<down>28</down>
		<up>30</up>
		<laterale>66</laterale>
	</NodoCella>


	<NodoCella>
		<id>30</id>
		<XCOR>200</XCOR>
		<YCOR>440</YCOR>
		<text>cinqOrg</text>
		<down>29</down>
		<up>31</up>
		<laterale></laterale>
	</NodoCella>

	<NodoCella>
		<id>31</id>
		<XCOR>150</XCOR>
		<YCOR>440</YCOR>
		<text>imprevisti</text>
		<down>30</down>
		<up>32</up>
		<laterale></laterale>
	</NodoCella>

	<NodoCella>
		<id>32</id>
		<XCOR>130</XCOR>
		<YCOR>400</YCOR>
		<text>isola plastica</text>
		<down>31</down>
		<up>33</up>
		<laterale></laterale>
	</NodoCella>


	<NodoCella>
		<id>33</id>
		<XCOR>100</XCOR>
		<YCOR>370</YCOR>
		<text>jolly</text>
		<down>32</down>
		<up>34</up>
		<laterale></laterale>
	</NodoCella>

	<NodoCella>
		<id>34</id>
		<XCOR>60</XCOR>
		<YCOR>365</YCOR>
		<text>cinqVetro</text>
		<down>33</down>
		<up>35</up>
		<laterale></laterale>
	</NodoCella>

	<NodoCella>
		<id>35</id>
		<XCOR>60</XCOR>
		<YCOR>330</YCOR>
		<text>centoCarta</text>
		<down>34</down>
		<up>36</up>
		<laterale></laterale>
	</NodoCella>

	<NodoCella>
		<id>36</id>
		<XCOR>60</XCOR>
		<YCOR>300</YCOR>
		<text>cinqPlastica</text>
		<down>35</down>
		<up>37</up>
		<laterale>71</laterale>
	</NodoCella>

	<NodoCella>
		<id>37</id>
		<XCOR>60</XCOR>
		<YCOR>260</YCOR>
		<text>centoOrg</text>
		<down>36</down>
		<up>38</up>
		<laterale></laterale>
	</NodoCella>

	<NodoCella>
		<id>38</id>
		<XCOR>40</XCOR>
		<YCOR>230</YCOR>
		<text>jolly</text>
		<down>37</down>
		<up>39</up>
		<laterale></laterale>
	</NodoCella>

	<NodoCella>
		<id>39</id>
		<XCOR>40</XCOR>
		<YCOR>190</YCOR>
		<text>centoIndif</text>
		<down>38</down>
		<up>40</up>
		<laterale></laterale>
	</NodoCella>

	<NodoCella>
		<id>40</id>
		<XCOR>60</XCOR>
		<YCOR>160</YCOR>
		<text>isola carta</text>
		<down>39</down>
		<up>41</up>
		<laterale></laterale>
	</NodoCella>

	<NodoCella>
		<id>41</id>
		<XCOR>100</XCOR>
		<YCOR>140</YCOR>
		<text>imprevisti</text>
		<down>40</down>
		<up>42</up>
		<laterale></laterale>
	</NodoCella>

	<NodoCella>
		<id>42</id>
		<XCOR>130</XCOR>
		<YCOR>110</YCOR>
		<text>cinqMetallo</text>
		<down>41</down>
		<up>43</up>
		<laterale></laterale>
	</NodoCella>
	<NodoCella>
		<id>43</id>
		<XCOR>170</XCOR>
		<YCOR>100</YCOR>
		<text>centoVetro</text>
		<down>42</down>
		<up>44</up>
		<laterale>77</laterale>

	</NodoCella>

	<NodoCella>
		<id>44</id>
		<XCOR>220</XCOR>
		<YCOR>70</YCOR>
		<text>imprevisti</text>
		<down>43</down>
		<up>45</up>
		<laterale></laterale>
	</NodoCella>
	<NodoCella>
		<id>45</id>
		<XCOR>260</XCOR>
		<YCOR>50</YCOR>
		<text>centoPlastica</text>
		<down>44</down>
		<up>46</up>
		<laterale></laterale>
	</NodoCella>
	<NodoCella>
		<id>46</id>
		<XCOR>300</XCOR>
		<YCOR>50</YCOR>
		<text>cinqIndif</text>
		<down>45</down>
		<up>47</up>
		<laterale></laterale>
	</NodoCella>
	<NodoCella>
		<id>47</id>
		<XCOR>345</XCOR>
		<YCOR>50</YCOR>
		<text>imprevisti</text>
		<down>46</down>
		<up>1</up>
		<laterale></laterale>
	</NodoCella>

	<NodoCella>
		<id>48</id>
		<XCOR>590</XCOR>
		<YCOR>110</YCOR>
		<text>centoMetallo</text>
		<down>6</down>
		<up>49</up>
		<laterale></laterale>
	</NodoCella>

	<NodoCella>
		<id>49</id>
		<XCOR>540</XCOR>
		<YCOR>120</YCOR>
		<text>cinqCarta</text>
		<down>48</down>
		<up>50</up>
		<laterale></laterale>
	</NodoCella>

	<NodoCella>
		<id>50</id>
		<XCOR>520</XCOR>
		<YCOR>140</YCOR>
		<text>imprevisti</text>
		<down>49</down>
		<up>51</up>
		<laterale></laterale>
	</NodoCella>

	<NodoCella>
		<id>51</id>
		<XCOR>500</XCOR>
		<YCOR>170</YCOR>
		<text>cinqOrg</text>
		<down>50</down>
		<up>52</up>
		<laterale></laterale>
	</NodoCella>

	<NodoCella>
		<id>52</id>
		<XCOR>500</XCOR>
		<YCOR>210</YCOR>
		<text>dieciIndif</text>
		<down>51</down>
		<up>-1</up>
		<laterale></laterale>
	</NodoCella>

	<NodoCella>
		<id>53</id>
		<XCOR>750</XCOR>
		<YCOR>255</YCOR>
		<text>jolly</text>
		<down>13</down>
		<up>54</up>
		<laterale></laterale>
	</NodoCella>

	<NodoCella>
		<id>54</id>
		<XCOR>710</XCOR>
		<YCOR>255</YCOR>
		<text>centoIndif</text>
		<down>53</down>
		<up>55</up>
		<laterale></laterale>
	</NodoCella>

	<NodoCella>
		<id>55</id>
		<XCOR>670</XCOR>
		<YCOR>255</YCOR>
		<text>imprevisti</text>
		<down>54</down>
		<up>56</up>
		<laterale></laterale>
	</NodoCella>

	<NodoCella>
		<id>56</id>
		<XCOR>630</XCOR>
		<YCOR>255</YCOR>
		<text>isola metallo</text>
		<down>55</down>
		<up>57</up>
		<laterale></laterale>
	</NodoCella>

	<NodoCella>
		<id>57</id>
		<XCOR>590</XCOR>
		<YCOR>255</YCOR>
		<text>centoOrg</text>
		<down>56</down>
		<up>58</up>
		<laterale></laterale>
	</NodoCella>

	<NodoCella>
		<id>58</id>
		<XCOR>550</XCOR>
		<YCOR>255</YCOR>
		<text>jolly</text>
		<down>57</down>
		<up>59</up>
		<laterale></laterale>
	</NodoCella>

	<NodoCella>
		<id>59</id>
		<XCOR>510</XCOR>
		<YCOR>255</YCOR>
		<text>dieciPlastica</text>
		<down>58</down>
		<up>-1</up>
		<laterale></laterale>
	</NodoCella>

	<NodoCella>
		<id>60</id>
		<XCOR>595</XCOR>
		<YCOR>430</YCOR>
		<text>centoCarta</text>
		<down>20</down>
		<up>61</up>
		<laterale></laterale>
	</NodoCella>


	<NodoCella>
		<id>61</id>
		<XCOR>565</XCOR>
		<YCOR>410</YCOR>
		<text>imprevisti</text>
		<down>60</down>
		<up>62</up>
		<laterale></laterale>
	</NodoCella>

	<NodoCella>
		<id>62</id>
		<XCOR>530</XCOR>
		<YCOR>390</YCOR>
		<text>isola organica</text>
		<down>61</down>
		<up>63</up>
		<laterale></laterale>
	</NodoCella>

	<NodoCella>
		<id>63</id>
		<XCOR>510</XCOR>
		<YCOR>360</YCOR>
		<text>jolly</text>
		<down>62</down>
		<up>64</up>
		<laterale></laterale>
	</NodoCella>

	<NodoCella>
		<id>64</id>
		<XCOR>485</XCOR>
		<YCOR>335</YCOR>
		<text>cinqIndif</text>
		<down>63</down>
		<up>65</up>
		<laterale></laterale>
	</NodoCella>

	<NodoCella>
		<id>65</id>
		<XCOR>450</XCOR>
		<YCOR>310</YCOR>
		<text>dieciVetro</text>
		<down>64</down>
		<up>-1</up>
		<laterale></laterale>
	</NodoCella>

	<NodoCella>
		<id>66</id>
		<XCOR>270</XCOR>
		<YCOR>430</YCOR>
		<text>jolly</text>
		<down>29</down>
		<up>67</up>
		<laterale></laterale>
	</NodoCella>

	<NodoCella>
		<id>67</id>
		<XCOR>310</XCOR>
		<YCOR>410</YCOR>
		<text>centoPlastica</text>
		<down>66</down>
		<up>68</up>
		<laterale></laterale>
	</NodoCella>

	<NodoCella>
		<id>68</id>
		<XCOR>330</XCOR>
		<YCOR>380</YCOR>
		<text>cinqVetro</text>
		<down>67</down>
		<up>69</up>
		<laterale></laterale>
	</NodoCella>

	<NodoCella>
		<id>69</id>
		<XCOR>350</XCOR>
		<YCOR>360</YCOR>
		<text>imprevisti</text>
		<down>68</down>
		<up>70</up>
		<laterale></laterale>
	</NodoCella>

	<NodoCella>
		<id>70</id>
		<XCOR>390</XCOR>
		<YCOR>340</YCOR>
		<text>dieciCarta</text>
		<down>69</down>
		<up>-1</up>
		<laterale></laterale>
	</NodoCella>

	<NodoCella>
		<id>71</id>
		<XCOR>110</XCOR>
		<YCOR>260</YCOR>
		<text>jolly</text>
		<down>36</down>
		<up>72</up>
		<laterale></laterale>
	</NodoCella>

	<NodoCella>
		<id>72</id>
		<XCOR>160</XCOR>
		<YCOR>260</YCOR>
		<text>centoVetro</text>
		<down>71</down>
		<up>73</up>
		<laterale></laterale>
	</NodoCella>

	<NodoCella>
		<id>73</id>
		<XCOR>200</XCOR>
		<YCOR>260</YCOR>
		<text>imprevisti</text>
		<down>72</down>
		<up>74</up>
		<laterale></laterale>
	</NodoCella>

	<NodoCella>
		<id>74</id>
		<XCOR>240</XCOR>
		<YCOR>260</YCOR>
		<text>centoIndif</text>
		<down>73</down>
		<up>75</up>
		<laterale></laterale>
	</NodoCella>

	<NodoCella>
		<id>75</id>
		<XCOR>280</XCOR>
		<YCOR>260</YCOR>
		<text>jolly</text>
		<down>74</down>
		<up>76</up>
		<laterale></laterale>
	</NodoCella>

	<NodoCella>
		<id>76</id>
		<XCOR>320</XCOR>
		<YCOR>260</YCOR>
		<text>dieciMetallo</text>
		<down>75</down>
		<up>-1</up>
		<laterale></laterale>
	</NodoCella>

	<NodoCella>
		<id>77</id>
		<XCOR>240</XCOR>
		<YCOR>115</YCOR>
		<text>centoMetallo</text>
		<down>43</down>
		<up>78</up>
		<laterale></laterale>
	</NodoCella>

	<NodoCella>
		<id>78</id>
		<XCOR>280</XCOR>
		<YCOR>130</YCOR>
		<text>cinqPlastica</text>
		<down>77</down>
		<up>79</up>
		<laterale></laterale>
	</NodoCella>

	<NodoCella>
		<id>79</id>
		<XCOR>300</XCOR>
		<YCOR>155</YCOR>
		<text>cinqMetallo</text>
		<down>78</down>
		<up>80</up>
		<laterale></laterale>
	</NodoCella>


	<NodoCella>
		<id>80</id>
		<XCOR>330</XCOR>
		<YCOR>170</YCOR>
		<text>jolly</text>
		<down>79</down>
		<up>81</up>
		<laterale></laterale>
	</NodoCella>

	<NodoCella>
		<id>81</id>
		<XCOR>330</XCOR>
		<YCOR>210</YCOR>
		<text>imprevisti</text>
		<down>80</down>
		<up>82</up>
		<laterale></laterale>
	</NodoCella>

	<NodoCella>
		<id>82</id>
		<XCOR>370</XCOR>
		<YCOR>220</YCOR>
		<text>dieciOrg</text>
		<down>81</down>
		<up>-1</up>
		<laterale></laterale>
	</NodoCella>

</Root>





















